### ISSUE TITLE
Revert back to 1x1 plot

### ISSUE THREAD

**Issue by pwinskill** [mrc-ide/vivax#11]
On exit of `plot_output()` revert back to `par(mfrow = c(1, 1))`

**Comment by pwinskill** [comment]
`on.exit(par(mfrow = c(1, 1)))` ?

**Comment by giovannic** [comment]
Hey, I'm replacing this code by a vignette as [suggested by Rich originally](https://github.com/mrc-ide/vivax/pull/1#discussion_r376323363).

I'll put you on the PR to see if it works for you.
