### ISSUE TITLE
Standardise outputs for GTS report

### ISSUE THREAD

**Issue by giovannic** [mrc-ide/vivax#4]
We need to produce output which is in line with our existing Malaria model.

Next steps are to get example outputs so we can write tests for what they should look like.

**Comment by pwinskill** [comment]
Here's an example of an output file from the _Pf_ model. It's output for an administartive unit in Uganda, taken from some global simulation runs that will be similar to what we do for the GTS.

[Example_output.txt](https://github.com/mrc-ide/vivax/files/4170499/Example_output.txt)

I wouldn't worry too much about the sub-annual output timesteps as I think for the GTS runs it will be annual. Other than that, key elements will be

1. The epi outputs: clinical and severe incidence and prevalence statified by different age groups. We can discuss these age groups in advance if easier, but flexibility in their sepcification would be ideal.
2. The proportion of the population in different age groups. This is needed if we want to aggregate up to whole popualtion estimates, know what % of the popoualtion is eligable for age-specific inerventions and estimate DALYs. This will include the age groups for the epi output but might also include additional age-bands (e.g. we might have 2-10 years old as well as 5-10 years old)

You'll see this output also has intervention and treatment vriables. We probably won't use these directly (as we can produce output intervention numbers and associated costs directly from our coverage inputs), but they are often helpful for debugging or aiding understanding of what has been successfully implemented in a given simulation run.

**Comment by pwinskill** [comment]
If any of that output and/or formtting is particulary grim to recreate we also do always have the option of tweaking the _Pf_ model output format (either directly or in post)  as well

**Comment by giovannic** [comment]
Ok, I've had a look through the outputs and have some extra questions on the outputs:

 - prev_2_10 and prev_0_5. The pv model outputs clinical, PCR and LM prevalence. Which prevalence do we mean here? Or perhaps we mean the proportion of individuals in the D state?
 - smooth. How do you smooth results? Could we get away with not copying the smoothing code into this package?
 - severe disease doesn't appear to be modelled. Is that possible or am I missing something?
 - prop_age_u5, prop_age_smc, prop_age_epi. Could you explain what these are? The model currently outputs number of humans in the P state, I'm sure it can be extended to do these if necessary
 - I'm not clear on what is meant by trt and smc in the context of this model. Is this BS and PQ or something else?
 - Just to be clear, we don't need to include the MDA and vaccine columns because we're not modelling them.

**Comment by pwinskill** [comment]
- I'll check what prevalence measure the vivax model outputs.
- Smoothing can be done in post
- Quite possible severe disease isn't included. I'll add it onto my list of things to discuss with Michael
- prop_age_u5/smc/api: proportion of the population aged under 5, age eligable for SMC and age eligable for EPI respectively (we shouldn't need to replicate these in the vivax model)
- SMC isn't applicable for vivax and trt is just treatment coverage which is already in the vivax model (but we need to keep it named as it is (BS and PQ) so we can distinuguish from Pf treatment)
- We won't need MDA or vaccine elements of the vivax model
